### ISSUE TITLE
Feedback in case of wrong command

### ISSUE THREAD

**Issue by TheButterbrotMan** [ickerio/factions#45]
### Is your feature request related to a problem?

If you currently enter e.g. /f create, nothing happens, there is also no error message that you have to enter a name.

### Describe the solution you'd like.

I would appreciate a notification of what is missing.

![image](https://user-images.githubusercontent.com/64548098/169518248-6b736d53-17bc-4f3a-9c0d-ecb5af2c3631.png)

### Describe alternatives you've considered.

Try it out until it works.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by PyPylia** [comment]
This seems to have been a bug with how Brigadier (Mojang's command system) deals with aliases.
This has been fixed in the latest dev version, and now behaves correctly.
This patch will be rolled out in the next release (most likely 2.0.0).

If you believe this hasn't been correctly patched, please reopen this issue.
