### ISSUE TITLE
Add Faction name (and colour) to a players nametag and tab menu

### ISSUE THREAD

**Issue by Metacinnabar** [ickerio/factions#8]
### Description
Change the display name color of a player to the color of the faction they reside in. This would make it easier to differentiate between faction members easily.

**Comment by ickerio** [comment]
I am slightly opposed to this idea as some colors may make names harder or easier to see in different scenarios. Players should not be disadvantaged because they chose a "bad" faction colour. I think most factions players will be fairly familiar with who their fellow members are.

It's a cool idea if executed well but I'm not really sure that it's possible. I'm welcome to any ideas but if not I may close this with the wontfix label.

**Comment by GoodPro712** [comment]
I forgot to mention in my original issue that this would take affect in the tab menu, but I understand your concern on legibility. Another option would be to have a letter or symbol next to their name in the tab menu colored as their faction, although this sounds very tedious and possibly not worth the effort.

**Comment by ickerio** [comment]
I agree that it would be a good idea to display this info on the tab menu. A solution to the nametag problem would be the Faction name is just gray text underneath the players name. I'll experiment with this in the future, though this issue is not a priority for now.
