### ISSUE TITLE
Feature request: Ally or trust a player even if they are in another faction

### ISSUE THREAD

**Issue by CalXee** [ickerio/factions#9]
### Is your feature request related to a problem?

Currently, there is no way to help contribute to your friend's projects or builds if the two are in different factions.

### Describe the solution you'd like.

Using ``/f trust [playername]`` would allow a player to build and break blocks in faction chunks like the grief protection doesn't apply to them at all. They can also open chests and interact with blocks. However, they won't add faction power to the faction, and them dying won't cause the faction they are trusted in to lose faction power. A player can be trusted in as many factions as they would like, even if they are in another faction.

### Describe alternatives you've considered.

I have thought of allowing the player to be a part of multiple factions, and doing so would let the player add faction power to both factions. Idea is that if you are part of 2 factions, each faction you are part of only receives half of the faction power from you compared if you are in only 1 faction. For example, if every player gave a faction 20 power, if that player is in 2 factions they would give each faction 10 power, and also lose half the power. There is also a maximum number of factions you can be a part of. That is a pretty complicated implementation, so perhaps this but without fractioning the faction power you give to each faction.

### Agreements

- [X] #10
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

### Other

I feel these are cool features to help the mod. If you would like me to create another report for the alternative I described then I'll do that.

**Comment by GoodPro712** [comment]
I was just about to suggest this lol

**Comment by ickerio** [comment]
I agree this would be a great feature to have. I feel like the best way to implement this would be allowing factions to ally with each other. What this encompasses though, is up for debate.

If two factions are allied, can players
- still attack each other?
- trade with villagers and interact with entities on the other factions claim?
- break and place blocks on the other factions claim?
- open chests on the other factions claim?

I certainly encourage discussion about this issue but I don't think I'll prioritize this feature for now, though I still do plan on implementing it somewhere down the line.

**Comment by TheBrewingTea** [comment]
> 
> 
> I agree this would be a great feature to have. I feel like the best way to implement this would be allowing factions to ally with each other. What this encompasses though, is up for debate.
> 
> If two factions are allied, can players
> 
>     * still attack each other?
> 
>     * trade with villagers and interact with entities on the other factions claim?
> 
>     * break and place blocks on the other factions claim?
> 
>     * open chests on the other factions claim?
> 
> 
> I certainly encourage discussion about this issue but I don't think I'll prioritize this feature for now, though I still do plan on implementing it somewhere down the line.

A subscription to a warning system could be great: 
Factions>>[Warning] <player> from <faction> opened a chest
Factions>>[Warning] <player> from <faction> slain <entity>
Factions>>[Warning] <player> from <faction> broke [<number>] blocks

Also the ability to toggle what players can and can't do within the claim would be useful

**Comment by GoodPro712** [comment]
### Trust Commands
`/f trust` or `/f ally` to get information on how the Trust system works
`/f trust PLAYERNAME` to have your current faction trust PLAYERNAME
### Trust Settings
Another thing to consider is per player config, although this might make the factions database very large over large playerbases.
For example:
`/f trust PLAYERNAME settings SETTING OPTION` instead of `/f trust settings SETTING OPTION` for the setting to apply for all players.
Going by the theoretical fact that per player config doesn't exist, I would suggest setting commands such as:

`/f trust settings pvp OPTION` If the trusted player and the faction members can pvp.
`/f trust settings entityInteraction OPTION` If the trusted player can use entities such as villagers and boats within a claim.
`/f trust settings blockInteraction OPTION` If the trusted player can use blocks such as trapdoors within a claim.
`/f trust settings storageInteraction OPTION` If the trusted player can open storage blocks such as chests within a claim.
`/f trust settings worldInteraction OPTION` If the trusted player can break or place blocks within a claim.
`/f trust settings itemUse OPTION` If the player can use items such as food or rockets within a claim.

With `OPTION` being either `true`, `false`, or `warn`, but also allowing special cases such as `pvp` having a `fistOnly` option for example.
I suggest defaults for these options, in respective order, being `fistOnly`, `true`, `true`, `false`, `true`, `true`.

I also suggest the player to be able to use the command `/f trust settings SETTING` without the `OPTION` parameter to display information on the setting.
